config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'organizations#scrum_teams'

  get '/scrum_teams' => 'organizations#scrum_teams'
  get '/services_teams' => 'organizations#services_teams'
  get '/users/' => 'users#index'
  match '/users/:id', :to => 'users#show', :as => :user,  :via => :get
  post 'goals/set_goal_priority' => 'goals#set_goal_priority'
  post 'goals/set_goal_frequency' => 'goals#set_goal_frequency'
  post 'goals/set_writer_coverage' => 'goals#set_writer_coverage'
  post 'goals/set_goal_support' => 'goals#set_goal_support'
  post 'goals/set_goal_work' => 'goals#set_goal_work'

  
  resources :organizations
  resources :people
  resources :goals
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base

  has_many :children, class_name: "Goal", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Goal"
  belongs_to :person
  
  #validates :name, :uniqueness => true
  validates :name, uniqueness: { scope: [:organization_id, :support_id] }

  delegate :organization, :to => :person, :allow_nil => true


  scope :priority, ->(priority) { where("priority = ?", priority) }
  scope :writer_coverage, ->(coverage) { where("writer_coverage = ?", coverage) }
  scope :low_risk, Proc.new { |area| area.support_status == 1 }
  scope :medium_risk, Proc.new { |area| area.support_status == 2 }
  scope :high_risk, Proc.new { |area| area.support_status == 3 }
  scope :unknown_risk, Proc.new { |area| area.support_status == 0 }

  
  def self.status(status)
    areas = Area.select { |a| a.support_status == status}
    return areas
  end
    
  def self.cost(cost)
    areas = Area.select { |a| a.burden == cost }
    return areas
  end
  
  def health

    if self.priority == nil || self.support == nil || self.priority == 0 
      0
    elsif self.priority > self.support + 1
      3
    elsif self.priority > self.support
      2
    else
      1
    end
   
  end

  def priority_narrative
    case self.priority
    when 0
      "Undetermined"
    when 1
      "Low"
    when 2
      "Medium"
    when 3
      "High"
    end
  end

  def support_narrative
    case self.health
    when 0
      "at Unknown Risk"
    when 1
      "at Very Little Risk"
    when 2
      "at Some Risk"
    when 3
      "at High Risk"
    end
  end



  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def new
    @goal = Goal.new
  end

  def show
    @goal = Goal.find(params[:id])
  end
  
  def create
    @goal = Goal.new(goal_params)
    # @goal.name = params[:name]
    # @goal.kind = params[:kind]
    # @goal.organization_id = params[:organization_id]
   
                   
    if @goal.save
      redirect_to @goal
    else
      render "new"
    end
  end
  
  def set_goal_priority
    @priority = params[:priority]
    @goal = Goal.find(params[:goal_id])
    @goal.priority = @priority

    if @goal.save
      respond_to do |format|
        format.js { render :action => 'update_priority_button.js.haml',
                           :locals => {:id => params[:goal_id],
                                       :priority => @goal.priority,
                                       :goal => @goal}}
        format.html 
      end
    end
  end

 def set_goal_frequency
    @frequency = params[:frequency]
    @goal = Goal.find(params[:goal_id])
    @goal.frequency = @frequency

    if @goal.save
      respond_to do |format|
        format.js { render :action => 'update_frequency_button.js.haml',
                           :locals => {:id => params[:goal_id],
                                       :frequency => @goal.frequency,
                                       :goal => @goal}}
        format.html 
      end
    end
 end

  def set_writer_coverage
    @writer_coverage = params[:writer_coverage]
    @goal = Goal.find(params[:goal_id])
    @goal.writer_coverage = @writer_coverage

    if @goal.save
      respond_to do |format|
        format.js { render :action => 'update_writer_coverage_button.js.haml',
                           :locals => {:id => params[:goal_id],
                                       :writer_coverage => @goal.writer_coverage,
                                       :goal => @goal}}
        format.html 
      end
    end
  end

  def set_goal_support
    @support = params[:support]
    @goal = Goal.find(params[:goal_id])
    @goal.support = @support

    if @goal.save
      respond_to do |format|
        format.js { render :action => 'update_support_button.js.haml',
                           :locals => {:id => params[:goal_id],
                                       :support => @goal.support,
                                       :goal => @goal}}
        format.html 
      end
    end
  end

  def destroy
    @goal = Goal.find(params[:id])

    if @goal.destroy
      respond_to do |format|
        format.html { redirect_to  organization_path(@goal.organization) }
      end
    else
      redirect_to @goal
    end
  end

  private
  def goal_params
    params.require(:goal).permit(:name, :kind, :organization_id)
  end
 
end

app/helpers/goals_helper.rb
module GoalsHelper


  def display_label(level, property)

    case level
    when 0
      label_class = "default"
      label = "No"
    when 1
      if property == "Coverage"
        label_class = "danger"
      else
        label_class = "success"
      end
      label = "Low"
    when 2
      label_class = "warning"
      label = "Medium"
    when 3
      if property == "Coverage"
        label_class = "success"
      else
        label_class = "danger"
      end
      label = "High"
    end

    capture_haml do
      haml_tag :span, class: "label-#{label_class} label" do
        haml_concat "#{label} #{property}"
      end
    end

  end

  def health_indicator(goal)
    case goal.health
    when 0
      glyph = "glyphicon-question-sign"
      indicator_class = "muted"
    when 1
      glyph = "glyphicon-ok"
      indicator_class = "success"
    when 2
      glyph = "glyphicon-warning-sign"
      indicator_class = "warning"
    when 3
      glyph = "glyphicon-fire"
      indicator_class = "danger"
    end

     capture_haml do
       haml_tag :span, class: "glyphicon #{glyph} text-#{indicator_class}"
     end    
  end

  
  def goal_button(goal,prop)
    case prop
    when "Support"
      goal_prop = goal.support
    when "Priority"
      goal_prop = goal.priority
    end
    
    case goal_prop
        when 0
          word = "No"
          btn_class = "Danger"
        when 1
          word = "Low"
          if prop == "Support"
            btn_class = "danger"
          else
            btn_class ="primary"
          end
        when 2
          word = "Medium"
          btn_class = "warning"
        when 3
          word = "High"
          if prop == "Support"
            btn_class = "success"
          else
            btn_class = "danger"
          end
        else
          word = ""
          btn_class = "primary"
    end

    if goal_prop == nil && current_user.try(:super?)
      word = "Set"
      disabled_state = nil
      btn_class = "default"
    elsif goal_prop == nil && !current_user.try(:super?)
      word = "Unset"
      disabled_state = "disabled"
      btn_class = "default"
    elsif !current_user.try(:super?)
      disabled_state = "disabled"
    end

    if current_user.try(:super?)
      capture_haml do
        haml_tag :button,
                 :class => "btn btn-#{btn_class} dropdown-toggle btn-xs",
                 "data-toggle" => "dropdown",
                 :type => "button",
                 :disabled => disabled_state do
          haml_concat "#{word} #{prop}"
          if current_user.try(:super?)
            haml_tag :span, :class => "caret"
          end
        end
      end
    else
      capture_haml do
          haml_tag :span,
                   :class => "btn btn-#{btn_class}" do
            haml_concat "#{word} #{prop}"
        end
      end
    end
  end


end

app/views/goals/_form.html.haml
= form_for(@goal, :html => {:class => "form-horizontal"} ) do |f|
  - if @goal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@goal.errors.count, "error")} prohibited this goal from being saved:"
      %ul
        - @goal.errors.full_messages.each do |msg|
          %li= msg
  .row
    .form-group
      = f.label :name, :class => 'col-sm-2 control-label'
      .col-sm-4
        = f.text_field :name, autofocus: true, :class => 'form-control'

  .row
    .form-group
      = f.label :Organization, :class => 'col-sm-2 control-label'
      .col-sm-4
        = f.collection_select :organization_id, Organization.all, :id, :name, {}, {:class => 'form-control'}

  .row
    .form-group
      = f.label :kind, :class => 'col-sm-2 control-label'
      .col-sm-4
        = f.select :kind, options_for_select(["Scrum Team Support", "Team Goal", "Organizational Goal", "Feature", "Company Goal", "Departmental Goal", "Initiative", "Current Work", "Future Work"],""),{:class => 'form-control'}


  .row
    %br    
    .actions
      = f.submit 'Save', :class => 'btn btn-primary'

app/views/goals/_health_field.html.haml
- goal = Goal.find(goal_id)
= health_indicator(goal)

app/views/goals/_index_row.html.haml
- goal = Goal.where("support_id = ? and name = ? and organization_id = ?", scrum_team.id, scrum_team.name, organization.id).last

- if goal
  - goal.health == 0 ? row_data = "unknown" : row_data = "known"

  %tr{:id => "goal_row_#{goal.id}", "data-value" => row_data }
    
    %td{:id => "goal_health_#{goal.id}", "data-value" => goal.health }
      = health_indicator(goal)
  
    %td{"data-value" => goal.name, :id => "goal_name_#{goal.id}"}
      - if goal.kind == "Scrum Team Support"
        = link_to goal.name, organization_path(:id => goal.support_id)
      - else
        = goal.name  

    %td{"data-value" => goal.priority, :id => "td_priority_#{goal.id}"}
      %div{:id => "priority-button-#{goal.id}"}
        = render :partial => "goals/priority_button", :locals => {:goal_id => goal.id}
           
    %td{"data-value" => goal.support, :id => "td_goal_support_#{goal.id}"}
      %div{:id => "support_button-#{goal.id}"}
        = render :partial => "goals/support_button", :locals => {:goal_id => goal.id}

  
  -# - if current_user.try(:super?) || current_user.try(:admin?) && current_user.team_id == area.team.id
  -#   %td{:id => "td_destroy_#{area.id}"}
  -#     = link_to edit_team_area_path(:id => area.id, :team_id => area.team.id), :class => "text-default" do
  -#       %span.glyphicon.glyphicon-pencil
  -#     &nbsp;
  -#     &nbsp;
  -#     = link_to team_area_path(:id => area.id, :team_id => area.team.id),  :method => :delete, :remote => true, :data =>  { confirm: "Really delete #{area.name}?" }, :class => "text-danger" do
  -#       %span.glyphicon.glyphicon-remove

app/views/goals/_priority_button.html.haml
- levels = {"High" => 3, "Medium" => 2, "Low" => 1, "None" => 0}
.btn-group.btn-group-xs
  != goal_button(goal_id,"Priority")
  - if current_user.try(:super?)
    %ul.dropdown-menu{:role => "menu"}
      - levels.each do |l,n|
        %li
          =link_to goals_set_goal_priority_path(:goal_id => goal_id, :priority => n), :remote => true, :method => :post do
            = l

app/views/goals/_status_field.html.haml
- goal = Goal.find(goal_id)
= health_indicator(goal)

app/views/goals/_support_button.html.haml
- levels = {"High" => 3, "Medium" => 2, "Low" => 1, "None" => 0}
.btn-group.btn-group-xs
  != goal_button(goal_id,"Support")
  - if current_user.try(:super?)
    %ul.dropdown-menu{:role => "menu"}
      - levels.each do |l,n|
        %li
          =link_to goals_set_goal_support_path(:goal_id => goal_id, :support => n), :remote => true, :method => :post do
            = l

app/views/goals/destroy_goal.js.haml
$("#goal_row_#{goal_id}").remove();

app/views/goals/edit.html.haml
%h1 Editing goal

= render 'form'

= link_to 'Show', @goal
\|
= link_to 'Back', goals_path

app/views/goals/index.html.haml
%h1 Listing goals

%table
  %thead
    %tr
      %th Name
      %th Kind
      %th
      %th
      %th

  %tbody
    - @goals.each do |goal|
      %tr
        %td= goal.name
        %td= goal.kind
        %td= link_to 'Show', goal
        %td= link_to 'Edit', edit_goal_path(goal)
        %td= link_to 'Destroy', goal, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Goal', new_goal_path

app/views/goals/new.html.haml
%h1 New goal

= render 'form'

= link_to 'Back', goals_path

app/views/goals/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @goal.name
%p
  %b Kind:
  = @goal.kind

= link_to 'Edit', edit_goal_path(@goal)
\|
= link_to 'Back', goals_path

app/views/goals/update_priority_button.js.haml
$("#priority-button-#{id}").html("#{j render(:partial => 'goals/priority_button', :locals => {:goal_id => id})}");
$("#td_priority_#{id}").attr("data-value", "#{priority}");
$("#td_priority_#{id}").parent('tr').attr("data-priority", "#{priority}");
$("#goal_health_#{id}").html("#{j render(:partial => 'goals/health_field', :locals => {:goal_id => id})}");
$("#goal_health_#{id}").attr("data-value", "#{goal.health}");

app/views/goals/update_support_button.js.haml
$("#support_button-#{id}").html("#{j render(:partial => 'goals/support_button', :locals => {:goal_id => id})}");
$("#td_support_#{id}").attr("data-value", "#{support}");
$("#td_support_#{id}").parent('tr').attr("data-support", "#{support}");
$("#goal_health_#{id}").html("#{j render(:partial => 'goals/health_field', :locals => {:goal_id => id})}");
$("#goal_health_#{id}").attr("data-value", "#{goal.health}");