config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'organizations#scrum_teams'

  get '/scrum_teams' => 'organizations#scrum_teams'
  get '/services_teams' => 'organizations#services_teams'
  get '/users/' => 'users#index'
  match '/users/:id', :to => 'users#show', :as => :user,  :via => :get
  post 'goals/set_goal_priority' => 'goals#set_goal_priority'
  post 'goals/set_goal_frequency' => 'goals#set_goal_frequency'
  post 'goals/set_writer_coverage' => 'goals#set_writer_coverage'
  post 'goals/set_goal_support' => 'goals#set_goal_support'
  post 'goals/set_goal_work' => 'goals#set_goal_work'

  
  resources :organizations
  resources :people
  resources :goals
  
end

app/models/organization.rb
class Organization < ActiveRecord::Base

  after_create :create_support_goals
  
  has_and_belongs_to_many :people
  has_many :children, class_name: "Organization", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Organization"
  validates :name, :uniqueness => true
  has_many :goals
  markdownize! :note
  
  def self.top_level
    puppet = Organization.find_by_name("Puppet Labs")
    where(parent_id: puppet.id)
  end

  def self.scrum_teams
    where(kind: "Scrum Team").order(:name)
  end

  def self.services_teams
    where(kind: "Services Team").order(:name)
  end

  def services_goals
    services_goals = Goal.where("kind = ? and support_id = ?", "Scrum Team Support", self.id)
    return services_goals
  end
  
  def self.services_teams_and_prod
    where(kind: "Services Team").order(:name)
  end

  
  def has_children
    self.children.count > 0 ? true : false
  end

  def has_people
    self.people.count > 0 ? true : false
  end

  def people_in_job(job)
    self.people.includes(:organizations).where(organizations: {name: job}).order(:fullname)
  end


  def scrum_support(scrum_team)
    support_goal = self.goals.where("support_id = ? and kind = ?", scrum_team.id, "Scrum Team Support").first
  end
  
  def create_support_goals

    if self.kind == "Services Team"
      Organization.scrum_teams.each do |scrum_team|
        goal = Goal.find_or_create_by(organization_id: id, support_id: scrum_team.id, name: scrum_team.name, kind: "Scrum Team Support")
        goal.save
      end
    end
  end
  
  
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController


  def destroy
    @organization = Organization.find(params[:id])

    if @organization.destroy
      respond_to do |format|
        format.html { redirect_to  organization_path(@organization.parent) }
      end
    else
      redirect_to @organization
    end
  end


  def show
    @organization = Organization.find(params[:id])
    @organizations = @organization.children
    @title = @organization.name
    @people = @organization.people
  end


  def index
    @organizations = Organization.top_level
    @title = "Organizations" 
  end

  def scrum_teams
    @organizations = Organization.find_by_name("Product and Technology").children.scrum_teams
    @title = "Product and Technology Scrum Teams"
  end

  def services_teams
    @organizations = Organization.find_by_name("Product and Technology").children.services_teams
    @title = "Product and Technology Services Teams"
  end

  
  def edit
    @organization = Organization.find(params[:id])
    @developers = Person.job("Engineering")
    @ux = Person.job("UX")
    @prod = Person.job("Product")
    @qa = Person.job("QA")
    @qe = Person.job("QE")
    @pm = Person.job("Project Management")
    @docs = Person.job("Technical Publications")
  end


  def update
    @organization = Organization.find(params[:id])
    if @organization.update_attributes(organization_params) && @organization.kind == "Scrum Team"
      redirect_to '/scrum_teams'
    elsif @organization.update_attributes(organization_params)
      redirect_to organization_path(@organization.parent)
    else
      render 'edit', alert: "Bad value in your edit form. Better talk to Mike."
    end
  end

  private
  def organization_params
    params.require(:organization).permit(:name, :kind, :parent_id, :languages, :note, :person_ids => [])
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper

  def list_people(organization)

    team_roles = ["Engineering", "UX", "QA", "Technical Publications"]
    puts organization.inspect
    team_roles.each do |job|
      render 'people_list', :job => job, :organization => organization
    end
        
  end

end

app/views/organizations/_child_orgs.html.haml
%table.table.sortable
  %thead
    %tr
      %th Name
      %th Kind
      %th
      %th
      %th

  %tbody
    - @organizations.each do |organization|
      %tr
        %td= link_to organization.name, organization
        %td= organization.kind
        %td= link_to 'Edit', edit_organization_path(organization)
        %td= link_to 'Destroy', organization, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/organizations/_form.html.haml
= form_for(@organization, :html => {:class => "form-horizontal"}) do |f|
  - if @organization.errors.any?
    #error_explanation
      %h2= "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
      %ul
        - @organization.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :name, autofocus: true, :class => 'form-control'

  .form-group
    =f.label :languages, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :languages, :class => 'form-control'
      
  .form-group
    = f.label :kind, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.select :kind, options_for_select(["Scrum Team","Services Team","Organization","Employee Group"],"Scrum Team"),:class => 'form-control'


  - if @organization.kind == "Scrum Team"

    .row
      = f.label "Engineers", :class => 'col-sm-2 control-label'
      .col-sm-2
        =f.collection_select :person_ids, @developers, :id, :fullname, {}, {:multiple => true, :class => 'form-control', 'style' => 'height:250px;'} 
    

      = f.label "QA", :class => 'col-sm-2 control-label'
      .col-sm-2
        =f.collection_select :person_ids, @qa, :id, :fullname, {}, {:multiple => true, :class => 'form-control', 'style' => 'height:250px;'} 

      = f.label "QE", :class => 'col-sm-2 control-label'
      .col-sm-2
        =f.collection_select :person_ids, @qe, :id, :fullname, {}, {:multiple => true, :class => 'form-control', 'style' => 'height:250px;'} 

    .row.top-buffer
      = f.label "Technical Publications", :class => 'col-sm-2 control-label'
      .col-sm-2
        =f.collection_select :person_ids, @docs, :id, :fullname, {}, {:multiple => true, :class => 'form-control', 'style' => 'height:250px;'} 

      = f.label "UX", :class => 'col-sm-2 control-label'
      .col-sm-2
        =f.collection_select :person_ids, @ux, :id, :fullname, {}, {:multiple => true, :class => 'form-control', 'style' => 'height:250px;'} 

      = f.label "Product", :class => 'col-sm-2 control-label'
      .col-sm-2
        =f.collection_select :person_ids, @prod, :id, :fullname, {}, {:multiple => true, :class => 'form-control', 'style' => 'height:250px;'}

    .row.top-buffer

      = f.label "Project Management", :class => 'col-sm-2 control-label'
      .col-sm-2
        =f.collection_select :person_ids, @pm, :id, :fullname, {}, {:multiple => true, :class => 'form-control', 'style' => 'height:250px;'} 

  .row.top-buffer

    = f.label "Notes", :class => 'col-sm-2 control-label'
    .col-sm-2
      =f.text_area :note,  {:class => 'form-control', 'style' => 'height:250px;width:500px'} 


  .row.top-buffer       
    .actions.col-sm-offset-2
      .col-sm-4
        = f.submit 'Save', :class => 'btn btn-primary'

app/views/organizations/_people_list.html.haml
- org = Organization.find_by_name(job)
- if org.kind == "Services Team" || org.name == "Product Management"
  - goal = org.scrum_support(@organization)
%strong
  = job
- if goal
  = health_indicator(goal)
- @organization.people_in_job(job).each do |person|
  %br
  = person.fullname
  

app/views/organizations/_scrum_team_tab.html.haml
%h4.top-buffer
  Overview

%strong
  Languages:
= @organization.languages

.top-buffer
  != @organization.rendered_note


%h4.top-buffer
  People 
- team_roles = ["Engineering", "Product Management", "Project Management", "UX", "QA", "QE", "Technical Publications"]
- team_roles.each_slice(3).each do |group|
  .row.top-buffer
    - group.each do |job|
      .col-sm-4
        = render 'people_list', :job => job

app/views/organizations/_services_goals_tab.html.haml
%table.table.sortable
  %thead
    %tr
      %th Health
      %th Team
      %th Priority
      %th Support
  %tbody
    - Organization.scrum_teams.each do |team|
      = render :partial => "goals/index_row", :locals => {:scrum_team => team, :organization => @organization}

app/views/organizations/edit.html.haml
%h3.col-sm-offset-1
  = "Editing #{@organization.name}"

= render 'form'

= link_to 'Show', @organization
\|
= link_to 'Back', organizations_path

app/views/organizations/index.html.haml
%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li.active
    Organizations


%table.table
  %thead
    %tr
      %th Name
      %th Kind
      %th
      %th
      %th

  %tbody
    - @organizations.each do |organization|
      %tr
        %td= link_to organization.name, organization
        %td= organization.kind
        %td= link_to 'Edit', edit_organization_path(organization)
        %td= link_to 'Destroy', organization, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.haml
%h1 New organization

= render 'form'

= link_to 'Back', organizations_path

app/views/organizations/scrum_teams.html.haml
%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li.active
    = @title

%table.table
  %thead
    %tr
      %th Team
      %th Dev
      %th Prod
      - Organization.services_teams.each do |services_team|
        %th
          = link_to services_team.name.scan(/[[:upper:]]/).join(""), services_team


  %tbody
    - @organizations.each do |organization|
      %tr
        %td= link_to organization.name, organization
        %td= organization.people_in_job("Engineering").count
        %td
          - prod = Organization.find_by_name("Product Management")
          - goal = prod.scrum_support(organization)
          - if goal
            = health_indicator(goal)
        
        - Organization.services_teams.each do |services_team|
          %td
            - goal = services_team.scrum_support(organization)
            - if goal
              = health_indicator(goal)
        %td= link_to 'Edit', edit_organization_path(organization)
        %td= link_to 'Destroy', organization, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Organization', new_organization_path

app/views/organizations/services_teams.html.haml
%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li.active
    Product and Technology Services Teams


%table.table
  %thead
    %tr
      %th Name
      %th

  %tbody
    - @organizations.each do |organization|
      %tr
        %td= link_to organization.name, organization
        %td= link_to 'Edit', edit_organization_path(organization)
        %td= link_to 'Destroy', organization, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Organization', new_organization_path

app/views/organizations/show.html.haml
%p#notice= notice

%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li
    = link_to "Organizations", organizations_path

  - if @organization.parent && @organization.parent.name != "Puppet Labs"
    %li
      = link_to @organization.parent.name, @organization.parent
    %li
      - if @organization.kind == "Scrum Team"
        = link_to "Scrum Teams", '/scrum_teams'
      - elsif @organization.kind == "Services Team"
        = link_to "Services Teams", '/services_teams'
    
      
  %li.active
    = @organization.name
  -# - if current_user.try(:super?)
  -#   %li
  -#     = link_to edit_team_area_path(@area, :team_id => @area.team.id) do
  -#       Edit


%ul{:role => "tablist", :class => "nav nav-tabs", :style => "margin-top:2em;"}
  - if @organization.kind == "Scrum Team"
    %li{:role => "presentation", :class => "active"}
      %a{:href => "#team_composition", :role => "tab", "data-toggle" => "tab"}
        Team Composition
  - else
    %li{:role => "presentation", :class => "active"}
      %a{:href => "#org_people", :role => "tab", "data-toggle" => "tab"}
        People
  - if @organization.kind == "Services Team" or @organization.name == "Product Management"
    %li{:role => "presentation"}
      %a{:href => "#services_goals", :role => "tab", "data-toggle" => "tab"}
        Services Goals
  %li{:role => "presentation"}
    %a{:href => "#team_goals", :role => "tab", "data-toggle" => "tab"}
      Team Goals
  - if @organization.has_children
    %li{:role => "presentation"}
      %a{:href => "#child_orgs", :role => "tab", "data-toggle" => "tab"}
        Child Organizations


%div.tab-content
  - if @organization.kind == "Scrum Team"
    %div.tab-pane.active{:id => "team_composition", :style => "padding-top:2em;"}
      = render 'scrum_team_tab'
  - else
    %div.tab-pane.active{:id => "org_people", :style => "padding-top:2em;"}
      %p
        People
    
  - if @organization.kind == "Services Team" or  @organization.name == "Product Management"
    %div.tab-pane.active{:id => "services_goals", :style => "padding-top:2em;", :role => "tabpanel"}
      = render 'services_goals_tab'

  %div.tab-pane{:id => "team_goals", :style => "padding-top:2em;", :role => "tabpanel"}
    %p
      Team Goals Here
      
  - if @organization.has_children
    %div.tab-pane{:id => "child_orgs", :style => "padding-top:2em;", :role => "tabpanel"}
      = render 'child_orgs'


%br.top-buffer
%br.top-buffer
= link_to 'Edit', edit_organization_path(@organization)
\|
= link_to 'Back', organizations_path